### ISSUE TITLE
Note Taker

### ISSUE THREAD

**Issue by JaredMabus** [JaredMabus/note-taker#1]
# User Story
User is able to write and save notes to organize their thoughts and keep track of task they need to complete.

## Acceptance Criteria
- [x] User is presented with a landing page with a link to a notes page
- [x] Click on the link > presented with a page with existing notes listed in the left-hand column, plus empty fields to enter a new note.
- [x] Enter new note title > a save icon appears in the navigation at the top of the page
- [x] Click the save icon > new note is saved and appears in the left-hand column with the other existing notes
- [x] Click existing note > the note appears in the right-hand column
- [x] Click on the Write icon in the nav > presented with empty fields to enter a new note title and the note's text in the right-hand column

## Task
- [x] Create API routes for managing note data
- [x] Create functionality for creating and deleting notes in the  db.json

 ## Design Mock
![image](https://user-images.githubusercontent.com/65479004/196051676-fc67d8b5-d328-4c97-9852-7e08186150f5.png)
![image](https://user-images.githubusercontent.com/65479004/196051688-c92a6ae9-82c8-4df9-a735-3db81dd0e4e1.png)
